[package]
name = "deamon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
homedir = "0.2.1"
lazy_static = "1.4.0"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
regex = "1.5"
anyhow = "1.0"
futures = "0.3"
nix = "0.25"
chrono = "0.4"
log = "0.4"
log4rs = "1"
axum = "0.4"
hyper = "0.14"
