[package]
name = "fs_meta"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.neon]
default-features = false
features = ["napi-5", "channel-api"]
